spring:
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret: "${JWT_SECRET}"
  name:
    access_token: "access_token"
    refresh_token: "refresh_token"
  expire-time:
    access-token-expire-time: "${ACCESS_TOKEN_EXPIRE_TIME}"
    refresh-token-expire-time: "${REFRESH_TOKEN_EXPIRE_TIME}"
  authorization: "Authorization"
  excluded-patterns: "${JWT_EXCLUDED_PATTERNS}"

cors:
  frontend: "${FRONTEND_URL}"
  methods: "${CORS_ALLOWED_METHODS}"
  allowed-headers: "${CORS_ALLOWED_HEADERS}"
  exposed-headers: "${CORS_EXPOSED_HEADERS}"
  age: "${CORS_MAX_AGE}"

cloud:
  aws:
    s3:
      bucket: "${S3_BUCKET}"
    credentials:
      access-key: "${S3_ACCESS_KEY}"
      secret-key: "${S3_SECRET_KEY}"
    region:
      name: "${AWS_REGION}"
    stack:
      auto: false

prefix:
  view-count: "post_view:"