spring:
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
    driver-class-name: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  data:
    redis:
      host: "${REDIS_HOST}"
      port: "${REDIS_PORT}"

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace

jwt:

  expire_time:

    refresh_token: ${REFRESH_TOKEN_EXPIRE_TIME}

frontend:


cloud:
  aws:
    s3:
      bucket: "${S3_BUCKET}"
    credentials:


    region:
      static: "${AWS_REGION}"
    stack:
      auto: false