name: KTB_Community CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  community-be-ci:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. 자바 세팅
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. 그래들 캐시(일단 의존성만 캐시)
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches  # 의존성, 플러그인, 스크립트
            ~/.gradle/wrapper # Gradle wrapper 배포본?
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          # 이 키로 변경사항 확인하는듯, 의존성은 거의 변경 안 되니 히트 적중율 높음
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. 빌드 & 테스트
      - name: Build & Test
        run: |
          chmod +x ./gradlew
          # ./gradlew clean test --no-daemon
          ./gradlew clean assemble --no-daemon

  community-be-cd:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-24.04
    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2. 짧은 SHA 태그용 변수 세팅
      - name: Set up image tag
        id: vars
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "short_sha=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
      
      # 3. Docker 세팅
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      # 4. 프라이빗 레지스트리 로그인
      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # 5. Docker 이미지 빌드 & 푸시
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}

      # 6. 배포
      - name: Deploy to private EC2
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.short_sha }}
        run: |
          echo "[deploy-step] IMAGE_TAG=${IMAGE_TAG}"
          
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          SSH_OPTS="-o StrictHostKeyChecking=no"
          
          ssh $SSH_OPTS ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} \
            "ssh $SSH_OPTS ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }} 'cd ~ && ./deploy.sh ${IMAGE_TAG}'"